### PR TITLE
add java opts option

### PR DESCRIPTION
**Pull request by ekimber**

### CODE REVIEW

**Comment by jlesquembre** [comment]
Thanks, while I want to add support for java options, I'm not sure if that's the right approach. I want to avoid recompile the derivation just because the java options changed.

Maybe a better approach could be to create a wrapper with `JDK_JAVA_OPTIONS`: https://docs.oracle.com/en/java/javase/11/tools/java.html

**Comment by ekimber** [comment]
Yes I can understand that you would prefer to do it that way, it is a runtime rather than compile time thing. Though in my use case the options are essential and won't change

**Comment by jlesquembre** [comment]
I'm reopening it to not forget about it

**Comment by jlesquembre** [comment]
@ekimber sorry for taking that long to address this. I'm merging it, it's nice to have that option available, we can optimize it in another PR

**Pull request merged**
